"""Explicit BTC reference contracts; exact prices retained for trading comparisons."""
from decimal import Decimal
import re

SPOT='crypto_prices_chainlink'
TWAP60='crypto_prices_twap_sixty'
TWAP30='crypto_prices_twap_thirty'
TWAP_RULE='This market will resolve to "Up" if the time-weighted average price (TWAP) of Bitcoin, generated by Chainlink, of the time range specified in the title is greater than or equal to the price at the beginning of that range. Otherwise, it will resolve to "Down". The resolution source for this market is information from Chainlink, specifically the BTC/USD TWAP data stream available at https://data.chain.link/streams/btc-usd-twap-60s-streams. Please note that this market is about the price according to the TWAP Chainlink data stream for the asset pair BTC/USD, not according to any other sources or spot markets.'

def classify_rule(description):
    normalized=' '.join(description.split())
    if normalized==TWAP_RULE:return 'TWAP60',TWAP60,'twap60-v1'
    lower=normalized.lower()
    if not any(x in lower for x in ('average','twap')) and all(x in lower for x in ('chainlink','bitcoin','beginning','end','greater than or equal')):
        return 'SPOT',SPOT,'spot-v1'
    return 'UNKNOWN',None,None

def observation(event,now):
    topic=event.get('topic');p=event.get('payload',{})
    if topic not in (SPOT,TWAP30,TWAP60) or not isinstance(p,dict) or p.get('symbol')!='btc/usd':return None
    if event.get('type')!='update':return None
    stamp=p.get('timestamp')
    if isinstance(stamp,bool) or not isinstance(stamp,(int,float)) or int(stamp)!=stamp:raise ValueError('invalid reference timestamp')
    source=stamp/1000
    if not -.25<=now-source<=10:raise ValueError('stale/future reference observation')
    if topic!=SPOT:
        window=60 if topic==TWAP60 else 30
        if p.get('window_s')!=window:raise ValueError('TWAP window mismatch')
        exact=p.get('full_accuracy_value')
        if not isinstance(exact,str) or not re.fullmatch(r'[0-9]{1,40}',exact):raise ValueError('TWAP exact E18 price missing')
        price=Decimal(exact).scaleb(-18)
    else:price=Decimal(str(p['value']))
    if not price.is_finite() or not 0<price<10_000_000:raise ValueError('invalid reference price')
    return {'price':float(price),'price_decimal':str(price),'source_ts':source,'source_ms':int(stamp),
            'received_at':now,'topic':topic,'source':'Chainlink TWAP 60s via RTDS' if topic==TWAP60 else 'Chainlink TWAP 30s via RTDS' if topic==TWAP30 else 'Chainlink spot via RTDS'}
